name: CI/CD for FastAPI with Docker to GCP

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/$personal-443910/fastapi-repo/fastapi-app:latest
          docker build -t $IMAGE_TAG .

      - name: Push Docker Image to Artifact Registry
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/$personal-443910/fastapi-repo/fastapi-app:latest
          docker push $IMAGE_TAG


  # Deploy to Google Cloud (e.g., GKE or Cloud Run)
  deploy_to_gcp:
    runs-on: ubuntu-latest
    needs: build_and_push  # Ensure the build job completes first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # For GKE Deployment (use if deploying to Kubernetes Engine)
      - name: Set up Google Cloud Kubernetes CLI
        run: |
          gcloud components install kubectl
          gcloud config set project $personal-443910
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $ZONE

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml

      # OR For Cloud Run Deployment (use if deploying to Cloud Run)
      - name: Deploy to Cloud Run
       run: |
          gcloud run deploy fastapi-app \
           --image gcr.io/$personal-443910/fastapi-app:$latest \
           --platform managed \
           --region us-central1 \
           --allow-unauthenticated \
           --port 8000