name: CI/CD for FastAPI with Docker to GCP

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  # Job to build and push Docker image to GCR and Artifact Registry
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud Registry (GCR)
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to authenticate with GCR
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build Docker Image
        run: |
          # Set image name and tag for GCR
          IMAGE_NAME=gcr.io/${{ vars.PROJECT_NAME }}/fastapi-app
          IMAGE_TAG=latest
          
          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image to GCR
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Log in to Artifact Registry
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to authenticate with Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Push Docker Image to Artifact Registry
        run: |
          # Set image name for Artifact Registry
          ARTIFACT_REGISTRY_IMAGE_NAME=us-central1-docker.pkg.dev/${{ vars.PROJECT_NAME }}/fastapi-repo/fastapi-app
          IMAGE_TAG=latest
          
          # Tag and push Docker image to Artifact Registry
          docker tag gcr.io/${{ vars.PROJECT_NAME }}/fastapi-app:$IMAGE_TAG $ARTIFACT_REGISTRY_IMAGE_NAME:$IMAGE_TAG
          docker push $ARTIFACT_REGISTRY_IMAGE_NAME:$IMAGE_TAG

  # Deploy to Google Cloud (e.g., GKE or Cloud Run)
  deploy_to_gcp:
    runs-on: ubuntu-latest
    needs: build_and_push  # Ensure the build job completes first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Deploy to Cloud Run using the image from Artifact Registry
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
           --image us-central1-docker.pkg.dev/${{ vars.PROJECT_NAME }}/fastapi-repo/fastapi-app:$IMAGE_TAG \
           --platform managed \
           --region us-central1 \
           --allow-unauthenticated \
           --port 8000
