name: CI/CD for FastAPI with Docker to GCP

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  # Job to build and push Docker image
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud Registry
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker Image
        run: |
          # Set image name and tag
          IMAGE_NAME=gcr.io/${{ vars.PROJECT_NAME }}/fastapi-app
          IMAGE_TAG=latest
          
          # Build and push Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  # Deploy to Google Cloud (e.g., GKE or Cloud Run)
  deploy_to_gcp:
    runs-on: ubuntu-latest
    needs: build_and_push  # Ensure the build job completes first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
           --image gcr.io/${{ vars.PROJECT_NAME }}/fastapi-app:$IMAGE_TAG \
           --platform managed \
           --region us-central1 \
           --allow-unauthenticated \
           --port 8000
